### ISSUE TITLE
Command Request

### ISSUE THREAD

**Issue by mckernant1** [descof2/discordbot#6]
Hi I am a simple discord user looking for a command to be added.

The command would be `!sad` and it would play the iconic lyrics from the juice wrld song lucid dreams
It would play "I STILL SEE YOUR SHADOWS IN MY ROOM"

Thanks
Tom

**Comment by descof2** [comment]
Hello Tom,

Thank you for your input on additional commands that could be added to
DarellBot, but no thanks.

Love,
Darell
Creator of DarellBot

**Comment by mckernant1** [comment]
U sook
